services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: rag_api
    shm_size: '2gb'
    mem_limit: 4g
    memswap_limit: 8g
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - CHROMA_HOST=chromadb
      - GEMINI_API_KEY=${GEMINI_API_KEY} # Use environment variable from host
      - MOCK_MODE=${MOCK_MODE:-false} # Enable mock mode for testing without Gemini API
    depends_on:
      chromadb:
        condition: service_healthy
    restart: on-failure

  chromadb:
    image: chromadb/chroma:0.5.3
    container_name: rag_chromadb
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/.chroma/index
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3

  # --- NEW SERVICE FOR AUTOMATED INGESTION ---
  ingestion_runner:
    build:
      context: .
      dockerfile: Dockerfile.api
    shm_size: '2gb'
    mem_limit: 4g
    memswap_limit: 8g
    environment:
      - CHROMA_HOST=chromadb
    depends_on:
      chromadb:
        condition: service_healthy
    command: ["python", "ingest.py"]
    profiles:
      - ingest
  # --- END NEW SERVICE ---

volumes:
  chroma_data:


